/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.calculator;

import net.calculator.model.CountryIso;
import net.calculator.service.NetPriceCalculatorService;
import net.calculator.service.imp.NetPriceCalculatorServiceImp;
import net.calculator.utility.TaxRateProvider;
public class App {
    public String getGreeting() {
        return "Net-Price-Calculator App";
    }

    public static void main(String[] args) {
        NetPriceCalculatorService service = new NetPriceCalculatorServiceImp();
        Double price = Double.parseDouble(System.getProperty("price", "100"));
        CountryIso countryIso = CountryIso.valueOf(System.getProperty("country", "DE"));
        System.out.println("Gross price: " + price);
        System.out.println("Tax rate: " + TaxRateProvider.getByCountry(countryIso));
        System.out.println("Net price: " + service.calculateNetPrice(price, countryIso));
    }
}
